[package]
authors = ["jD91mZM2 <me@krake.one>"]
description = "A work-in-progress language server for Nix, with syntax checking and basic completion"
keywords = ["rnix", "nix", "languageserver", "lsp"]
categories = ["text-editors", "parser-implementations", "development-tools::testing"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/nix-community/rnix-lsp"
edition = "2018"
name = "rnix-lsp"
version = "0.1.0"

[dependencies]
dirs = "2.0.2"
env_logger = "0.7.1"
lazy_static = "1.4"
libc = "0.2.66"
log = "0.4.8"
lsp-server = "0.3.1"
lsp-types = { version = "0.79.0", features = ["proposed"] }
nixpkgs-fmt = "1.2.0"
regex = "1"
rnix = "0.9.0"
rowan = "0.12.6"
serde = "1.0.104"
serde_json = "1.0.44"
manix = { git = "https://github.com/kreisys/manix", branch = "master" }
xdg = "2.2"
itertools = "0.9"
